Repository hanami/utils, pull requests merged in 2019-01, with the labels that each got.

#315 Ruby 2.6.0
  .circleci/config.yml
  .travis.yml
  lib/hanami/utils/kernel.rb
  spec/unit/hanami/utils/kernel_spec.rb
Labels: enhancement

#300 Fix #299 by adding require to lib/hanami/utils.rb
  lib/hanami/utils.rb
Labels: fix

#297 logger: fix default formatter for hashes
  lib/hanami/utils/query_string.rb
  spec/unit/hanami/logger_spec.rb
  spec/unit/hanami/utils/query_string_spec.rb
Labels: enhancement

#309 Agnostic ArgumentError's message check in utils/string_spec.rb
  spec/unit/hanami/utils/string_spec.rb
Labels: enhancement

#311 Remove `Utils::Class.load_from_pattern!`
  lib/hanami/utils/class.rb
  spec/unit/hanami/utils/class_spec.rb
Labels: breaking-change

#319 Remove Utils::Inflector
  Gemfile
  lib/hanami/utils/inflector.rb
  lib/hanami/utils/string.rb
  spec/isolation/hanami/utils/inflector/with_inflecto_spec.rb
  spec/isolation/hanami/utils/inflector/without_inflecto_spec.rb
  spec/support/fixtures/fixtures.rb
  spec/unit/hanami/utils/inflector_spec.rb
  spec/unit/hanami/utils/string_spec.rb
Labels: breaking-change

#320 Utils::Hash module
  lib/hanami/interactor.rb
  lib/hanami/logger/formatter.rb
  lib/hanami/utils/blank.rb
  lib/hanami/utils/hash.rb
  spec/unit/hanami/utils/blank_spec.rb
  spec/unit/hanami/utils/hash_spec.rb
Labels: breaking-change

#322 Remove Utils::Duplicable
  lib/hanami/utils/class_attribute/attributes.rb
  lib/hanami/utils/duplicable.rb
  lib/hanami/utils/hash.rb
  spec/unit/hanami/utils/duplicable_spec.rb
Labels: breaking-change
