Repository hanami/utils, pull requests merged in 2020-12, with the labels that each got.

#365 Do not mutate input hash when filter sensitive params
  lib/hanami/logger/filter.rb
  spec/unit/hanami/logger_spec.rb
Labels: bug, fix

#389 Allows Logger can filter an array of hash
  lib/hanami/logger/filter.rb
  spec/unit/hanami/logger_spec.rb
Labels: bug, fix

#385 Change archived gem "Transproc" for its successor "Dry::Transformer"
  hanami-utils.gemspec
  lib/hanami/utils/hash.rb
  lib/hanami/utils/string.rb
Labels: enhancement

#390 Transform `Utils::String` into module
  lib/hanami/utils/path_prefix.rb
  lib/hanami/utils/string.rb
  spec/unit/hanami/utils/blank_spec.rb
  spec/unit/hanami/utils/kernel_spec.rb
  spec/unit/hanami/utils/string_spec.rb
Labels: breaking-change, enhancement
